### ISSUE TITLE
Чат не работает в реальном времени

### ISSUE THREAD

**Issue by Pahomk** [RobertGoodman08/websocket_chat_laravel#1]
Здравствуйте. 
Хочу попробовать ваш проект, но не получается его завести должным образом.

Сделал всё по инструкции:
1. Распаковываем проект и открываем в phpstorm
2. Запускаем команду composer install
3. После чего, копируем из .env.example и создаем новый файл .env
4. В нем прописываем соединение с бд
5. Запускаем команду php artisan key:generate
6. Далее миграции php artisan migrate
7. Фронтенд npm install
8. И можно запустить сервер php artisan serve

По ходу выполнения пунктов ошибок не возникало.

После выполнения всех пунктов проект не запустился. 
Скриншот ошибки:
![image](https://github.com/RobertGoodman08/websocket_chat_laravel/assets/146883182/96b11a5a-5cb3-4ed6-8751-6c114a648667)

Проблему исправил вводом команды в новом окне терминала: _**npm run dev**_
Затем перешел на страницу регистрации с двух окон браузера и зарегистрировал двух пользователей. 

### Далее появилась новая и **основная** **проблема**
**Чат не работает в режиме реального времени.** Т.е. чтобы увидеть новые сообщения от другого пользователя нужно было обновлять страницу.
![image](https://github.com/RobertGoodman08/websocket_chat_laravel/assets/146883182/aacb92eb-f7d4-4a1f-a0b0-10fb5a100e85)

В консоли ничего кроме данных сообщений не выводится:
![image](https://github.com/RobertGoodman08/websocket_chat_laravel/assets/146883182/bf4973e5-a739-40f4-97e5-1aa2f65d4f68)

Я использую _OpenServer_

Подскажите пожалуйста, что я делаю не так?  
Заранее спасибо

**Comment by RobertGoodman08** [comment]
Здравствуйте, вам необходимо настроитьWebSocket-сервера. Если вы используете [Pusher](https://pusher.com/laravel/) вам необходимо настроить в файле .env 
PUSHER_APP_ID=your-app-id
PUSHER_APP_KEY=your-app-key
PUSHER_APP_SECRET=your-app-secret
PUSHER_APP_CLUSTER=your-app-cluster
PUSHER_APP_ENCRYPTED=true
. Если у вас ещё есть вопросы, вы можете их задать мне. Надеюсь, я смог вам помочь удачи вам.

**Comment by Pahomk** [comment]
Спасибо за ответ.
Я попробовал сделать то что вы написали, но это не помогло :(

Я отредактировал файл .env добавив туда следующие данные (изменённые строки выделены зеленой чертой):
![image](https://github.com/RobertGoodman08/websocket_chat_laravel/assets/115905749/d5ba4449-d455-4839-9c03-8e50cb023394)

После я перезапустил сервер и это не дало результата. 
**Чат _по прежнему_ не работает в реальном времени**. В консоли браузера ничего кроме этого нету:
![image](https://github.com/RobertGoodman08/websocket_chat_laravel/assets/115905749/18c7c4a6-61ed-4713-991f-fe8a536351ef)


_**Подскажите пожалуйста что ещё можно сделать?**_

Данные Pusher'а (на данный момент они актуальны):
![image](https://github.com/RobertGoodman08/websocket_chat_laravel/assets/115905749/541a7bdb-ef25-4900-9620-3a5c85c141a0)

app_id = "1705634"
key = "f78d6b10552099d153af"
secret = "2868d417944195e30563"
cluster = "eu"

**Comment by Pahomk** [comment]
Возможно у меня проблема из-за OpenServer'а. 
Мне кажется я что-то не так делаю.

Вот что у меня выводится в терминале.
![image](https://github.com/RobertGoodman08/websocket_chat_laravel/assets/115905749/cfa5ec82-3590-4ea7-82ba-5f209fbfc7e6)

![image](https://github.com/RobertGoodman08/websocket_chat_laravel/assets/115905749/95277694-af44-471d-82bb-6998240297a4)

Настройки OpenServer:
![image](https://github.com/RobertGoodman08/websocket_chat_laravel/assets/115905749/a981ef58-4f84-4c0d-8eb1-c72a5fa62706)
